// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportFlow.Api.Data;

#nullable disable

namespace SupportFlow.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportFlow.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Notifications");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_Notifications_TicketId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Notifications_UserId_CreatedAt");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Message_Length", "LENGTH(TRIM(\"Message\")) BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_Notifications_Title_Length", "LENGTH(TRIM(\"Title\")) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Tickets");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("IX_Tickets_AssignedAgentId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Tickets_CategoryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tickets_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Tickets_CustomerId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Tickets_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tickets_Status");

                    b.ToTable("Tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_ClosedAt", "\"ClosedAt\" IS NULL OR \"ClosedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_Tickets_Description_Length", "LENGTH(TRIM(\"Description\")) >= 10");

                            t.HasCheckConstraint("CK_Tickets_Priority", "\"Priority\" IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("CK_Tickets_Status", "\"Status\" IN ('Open', 'In Progress', 'Waiting for Customer', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("CK_Tickets_Title_Length", "LENGTH(TRIM(\"Title\")) BETWEEN 5 AND 200");

                            t.HasCheckConstraint("CK_Tickets_UpdatedAt", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_TicketAttachments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketAttachments_TicketId");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("IX_TicketAttachments_UploadedByUserId");

                    b.HasIndex("TicketId", "UploadedAt")
                        .HasDatabaseName("IX_TicketAttachments_TicketId_UploadedAt");

                    b.ToTable("TicketAttachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketAttachments_ContentType_NotEmpty", "LENGTH(TRIM(\"ContentType\")) BETWEEN 1 AND 150");

                            t.HasCheckConstraint("CK_TicketAttachments_FileName_NotEmpty", "LENGTH(TRIM(\"FileName\")) BETWEEN 1 AND 255");

                            t.HasCheckConstraint("CK_TicketAttachments_FilePath_NotEmpty", "LENGTH(TRIM(\"FilePath\")) BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK_TicketCategories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_TicketCategories_Name");

                    b.ToTable("TicketCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketCategories_Name_NotEmpty", "LENGTH(TRIM(\"Name\")) >= 2");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_TicketMessages");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_TicketMessages_SenderId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketMessages_TicketId");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("IX_TicketMessages_TicketId_CreatedAt");

                    b.ToTable("TicketMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketMessages_Message_Length", "LENGTH(TRIM(\"Message\")) BETWEEN 1 AND 10000");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_TicketStatusHistories");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_TicketStatusHistories_ChangedByUserId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketStatusHistories_TicketId");

                    b.HasIndex("TicketId", "ChangedAt")
                        .HasDatabaseName("IX_TicketStatusHistories_TicketId_ChangedAt");

                    b.ToTable("TicketStatusHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketStatusHistories_NewStatus", "\"NewStatus\" IN ('Open', 'In Progress', 'Waiting for Customer', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("CK_TicketStatusHistories_OldStatus", "\"OldStatus\" IS NULL OR \"OldStatus\" IN ('Open', 'In Progress', 'Waiting for Customer', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("CK_TicketStatusHistories_StatusChanged", "\"OldStatus\" IS NULL OR \"OldStatus\" <> \"NewStatus\"");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Customer");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Email_NotEmpty", "LENGTH(TRIM(\"Email\")) > 0");

                            t.HasCheckConstraint("CK_Users_FullName_NotEmpty", "LENGTH(TRIM(\"FullName\")) >= 2");

                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Customer', 'SupportAgent', 'Admin')");
                        });
                });

            modelBuilder.Entity("SupportFlow.Api.Models.Notification", b =>
                {
                    b.HasOne("SupportFlow.Api.Models.Ticket", "Ticket")
                        .WithMany("Notifications")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notifications_Tickets_TicketId");

                    b.HasOne("SupportFlow.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users_UserId");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.Ticket", b =>
                {
                    b.HasOne("SupportFlow.Api.Models.User", "AssignedAgent")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Tickets_Users_AssignedAgentId");

                    b.HasOne("SupportFlow.Api.Models.TicketCategory", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_TicketCategories_CategoryId");

                    b.HasOne("SupportFlow.Api.Models.User", "Customer")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Users_CustomerId");

                    b.Navigation("AssignedAgent");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketAttachment", b =>
                {
                    b.HasOne("SupportFlow.Api.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketAttachments_Tickets_TicketId");

                    b.HasOne("SupportFlow.Api.Models.User", "UploadedByUser")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TicketAttachments_Users_UploadedByUserId");

                    b.Navigation("Ticket");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketMessage", b =>
                {
                    b.HasOne("SupportFlow.Api.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TicketMessages_Users_SenderId");

                    b.HasOne("SupportFlow.Api.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketMessages_Tickets_TicketId");

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketStatusHistory", b =>
                {
                    b.HasOne("SupportFlow.Api.Models.User", "ChangedByUser")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TicketStatusHistories_Users_ChangedByUserId");

                    b.HasOne("SupportFlow.Api.Models.Ticket", "Ticket")
                        .WithMany("StatusHistories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketStatusHistories_Tickets_TicketId");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.TicketCategory", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SupportFlow.Api.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("Notifications");

                    b.Navigation("SentMessages");

                    b.Navigation("StatusChanges");

                    b.Navigation("UploadedAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
